# Generated by Django 4.1.7 on 2023-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteaccess",
            name="api_key",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="remoteaccess",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
