# Generated by Django 4.1.7 on 2023-04-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0007_alter_organization_uuid"),
        ("core", "0004_alter_area_uuid"),
        ("client", "0004_alter_remoteaccess_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteaccess",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.area",
            ),
        ),
        migrations.AddField(
            model_name="remoteaccess",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="org.organization",
            ),
        ),
    ]
