# Generated by Django 4.1.7 on 2023-03-21 14:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitalservice",
            options={
                "verbose_name": "Service numérique",
                "verbose_name_plural": "Services numériques",
            },
        ),
        migrations.AlterModelOptions(
            name="digitalservicecontact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="digitaluse",
            options={
                "verbose_name": "Usage numérique",
                "verbose_name_plural": "Usages numériques",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Objet"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Pièce"},
        ),
        migrations.AlterField(
            model_name="digitalservice",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
