# Generated by Django 4.1.7 on 2023-03-21 14:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("core", "0002_alter_digitalservice_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalservice",
            name="items",
        ),
        migrations.RemoveField(
            model_name="digitalservice",
            name="tags",
        ),
        migrations.AddField(
            model_name="digitalservice",
            name="uses",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="core.digitaluse"
            ),
        ),
        migrations.AlterField(
            model_name="digitalservice",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.zone",
            ),
        ),
        migrations.AlterField(
            model_name="digitaluse",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="uses", to="core.item"
            ),
        ),
        migrations.AlterField(
            model_name="digitaluse",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
