# Generated by Django 4.1.7 on 2023-04-19 13:10

from django.db import migrations

import uuid

def gen_uuid(apps, schema_editor):
    Area = apps.get_model('core', 'Area')
    for row in Area.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_area_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
