# Generated by Django 4.1.7 on 2023-03-21 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_digitalservice_items_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
