# Generated by Django 4.1.7 on 2023-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalservice",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
