# Generated by Django 4.1.7 on 2023-04-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_digitalservice_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalservice",
            name="use",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="core.digitaluse",
            ),
        ),
        migrations.AlterField(
            model_name="digitalservice",
            name="uses",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="core.digitaluse"
            ),
        ),
    ]
