# Generated by Django 4.1.7 on 2023-04-07 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_digitalservice_use_alter_digitalservice_uses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalservice",
            name="uses",
        ),
    ]
