# Generated by Django 4.1.7 on 2023-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_digitalservice_uuid_alter_digitaluse_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="main_color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
