# Generated by Django 4.1.7 on 2023-04-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_digitalservice_uses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Zone d'activité",
                "verbose_name_plural": "Zones d'activité",
            },
        ),
        migrations.RemoveField(
            model_name="digitalservice",
            name="zone",
        ),
        migrations.DeleteModel(
            name="Zone",
        ),
        migrations.AddField(
            model_name="digitalservice",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.area",
            ),
        ),
    ]
