# Generated by Django 4.2.1 on 2023-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_image_room_video_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='light_ctrl',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='Numéro du contrôleur de lumière'),
        ),
        migrations.AddField(
            model_name='item',
            name='light_pin',
            field=models.CharField(blank=True, choices=[('AO', 'AO'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('B0', 'B0'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7')], max_length=2, null=True, verbose_name='Numéro de la broche de la LED'),
        ),
    ]
