# Generated by Django 4.2.1 on 2023-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_light_ctrl_item_light_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='light_pin',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Numéro de la broche du ruban LED'),
        ),
    ]
