# Generated by Django 4.2.1 on 2023-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_light_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
