# Generated by Django 4.2.4 on 2023-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_room_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['position'], 'verbose_name': 'Pièce'},
        ),
        migrations.AlterField(
            model_name='room',
            name='light_pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de la broche du ruban LED'),
        ),
    ]
