# Generated by Django 4.2.4 on 2023-08-30 16:03

from django.db import migrations


def rename_media_file(apps, schema_editor):
    Room = apps.get_model('core', 'Room')
    Item = apps.get_model('core', 'Item')

    Room.objects.all().update(video=None)
    Item.objects.all().update(image=None)

    for room in Room.objects.all():
        room.save()
    
    for item in Item.objects.all():
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_room_next_room'),
    ]

    operations = [
        migrations.RunPython(rename_media_file, reverse_code=migrations.RunPython.noop),
    ]
