# Generated by Django 4.2.4 on 2023-09-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230830_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='light_pin',
        ),
    ]
