# Generated by Django 4.2.4 on 2023-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_digitalservice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalservice',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DigitalServiceContact',
        ),
    ]
