# Generated by Django 4.2.4 on 2023-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_digitalservice_area_delete_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalservice',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
