# Generated by Django 5.0.1 on 2024-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='tags',
        ),
        migrations.AddField(
            model_name='contribution',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
