# Generated by Django 4.2.4 on 2023-10-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='feedback.question'),
        ),
    ]
