# Generated by Django 4.2.4 on 2023-10-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_answer_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_at',)},
        ),
    ]
