# Generated by Django 4.1.7 on 2023-04-14 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0002_organizationapikey_creator_user_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationapikey",
            old_name="creator",
            new_name="created_by",
        ),
    ]
