# Generated by Django 4.1.7 on 2023-04-19 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0004_alter_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
