# Generated by Django 4.1.7 on 2023-04-19 13:21

from django.db import migrations

import uuid

from org.models import Organization

def gen_uuid(apps, schema_editor):
    Organization = apps.get_model('org', 'Organization')
    for row in Organization.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):
    dependencies = [
        ("org", "0005_organization_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
