# Generated by Django 4.1.7 on 2023-04-19 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0006_auto_20230419_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
