# Generated by Django 4.2.4 on 2023-10-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_alter_organization_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='area',
        ),
    ]
