# Generated by Django 5.0.6 on 2024-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('B', 'Booléen'), ('I', 'Entier'), ('S', 'Chaine de caractères'), ('D', 'Décimal')], max_length=1)),
                ('bool_value', models.BooleanField(default=False)),
                ('int_value', models.IntegerField(default=0)),
                ('str_value', models.CharField(max_length=500)),
                ('dec_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Paramètre',
            },
        ),
    ]
