# Generated by Django 5.0.6 on 2024-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='dec_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='int_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='str_value',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
