# Generated by Django 5.0.6 on 2024-05-31 09:30

from django.db import migrations


def init_parameter_for_tickets(apps, schema_editor):
    """Ajout du paramètre pour l'impression des tickets"""
    Parameter = apps.get_model("parameters", "Parameter")
    ticket_parameter = Parameter(
        name = "Impression tickets",
        category = "B",
        bool_value = True,
    )
    ticket_parameter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_parameter_slug_alter_parameter_dec_value_and_more'),
    ]

    operations = [
        migrations.RunPython(init_parameter_for_tickets),
    ]
