# Generated by Django 4.2.4 on 2023-08-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_room_next_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='videos/scenarii/')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioItemChoiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/scenarii/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioUseChoiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/scenarii/')),
                ('item_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.scenarioitemchoicestep')),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.digitaluse')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioRoomChoiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenarioitemchoicestep',
            name='room_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.scenarioroomchoicestep'),
        ),
    ]
